apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: poc
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/jenkins_home

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi