kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: jmeter-slaves-hpa 
spec:
  maxReplicas: 10
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: app/v1 
    kind: Deployment 
    name: jmeter-slaves
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 60
