apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-physical-volume
  labels:
    type: local
spec:
  storageClassName: managed-premium
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/influxdb"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-timeshift-proxy-physical-volume
  labels:
    type: local
spec:
  storageClassName: managed-premium
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/influxdb-timeshift-proxy"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-timeshift-proxy-pvc
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi

---
