apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-home-physical-volume
  labels:
    type: local
spec:
  storageClassName: managed-premium
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/grafana-home"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-home-pvc
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-conf-physical-volume
  labels:
    type: local
spec:
  storageClassName: managed-premium
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/grafana-conf"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-conf-pvc
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi

---