apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
spec:
  storageClassName: azurefile
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/influxdb/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
