apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-jmeter
  labels:
    app: influxdb-jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-jmeter
  template:
    metadata:
      labels:
        app: influxdb-jmeter
    spec:
      volumes:
      - name: influxdb-pv
        persistentVolumeClaim:
          claimName: influxdb-pvc
      containers:
        - image: acrpocs.azurecr.io/influxdb:latest
          imagePullPolicy: IfNotPresent
          name: influxdb
          ports:
            - containerPort: 8083
              name: influx
            - containerPort: 8086
              name: api
            - containerPort: 2003
              name: graphite
          volumeMounts:
          - name: influxdb-pv
            mountPath: /var/lib/influxdb/
